GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Muhammad Aja",
    "email": "muhrofi01@gmail.com",
    "password": "spasi1kali",
    "confPassword": "spasi2kali"
}